"""
Voice Service for the Knowledge Mesh Desktop application.

This module provides a service that enables voice recognition and synthesis
for natural language interaction with the application.
"""

import asyncio
import datetime
import logging
import os
import re
import tempfile
from enum import Enum, auto
from pathlib import Path
from typing import Dict, List, Optional, Set, Tuple, Union, Any, Callable

import numpy as np

from ..core.config import Config
from ..core.events import EventType, publish, subscribe, event_bus

logger = logging.getLogger(__name__)


class VoiceCommand:
    """
    Represents a voice command recognized by the system.
    
    This class provides a standardized representation of voice commands
    from various recognition engines.
    """
    
    def __init__(
        self,
        id: str,
        text: str,
        confidence: float,
        timestamp: Optional[datetime.datetime] = None,
        metadata: Optional[Dict[str, Any]] = None,
    ):
        """
        Initialize a voice command.
        
        Args:
            id: The unique identifier for the command
            text: The recognized text of the command
            confidence: The confidence level of the recognition (0.0 to 1.0)
            timestamp: The timestamp of the command
            metadata: Additional metadata for the command
        """
        self.id = id
        self.text = text
        self.confidence = confidence
        self.timestamp = timestamp or datetime.datetime.now()
        self.metadata = metadata or {}
        self.intent = None
        self.entities = []
    
    @property
    def is_confident(self) -> bool:
        """Check if the recognition confidence is high enough."""
        return self.confidence >= 0.7
    
    @property
    def is_recent(self) -> bool:
        """Check if the command is recent (less than 10 seconds old)."""
        if self.timestamp:
            return (datetime.datetime.now() - self.timestamp) < datetime.timedelta(seconds=10)
        return False
    
    def to_dict(self) -> Dict[str, Any]:
        """
        Convert the command to a dictionary.
        
        Returns:
            A dictionary representation of the command
        """
        return {
            "id": self.id,
            "text": self.text,
            "confidence": self.confidence,
            "timestamp": self.timestamp.isoformat() if self.timestamp else None,
            "metadata": self.metadata,
            "intent": self.intent,
            "entities": self.entities,
            "is_confident": self.is_confident,
            "is_recent": self.is_recent,
        }
    
    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "VoiceCommand":
        """
        Create a command from a dictionary.
        
        Args:
            data: The dictionary representation of the command
            
        Returns:
            A VoiceCommand object
        """
        timestamp = None
        if data.get("timestamp"):
            try:
                timestamp = datetime.datetime.fromisoformat(data["timestamp"])
            except ValueError:
                pass
        
        command = cls(
            id=data.get("id", ""),
            text=data.get("text", ""),
            confidence=data.get("confidence", 0.0),
            timestamp=timestamp,
            metadata=data.get("metadata", {}),
        )
        
        command.intent = data.get("intent")
        command.entities = data.get("entities", [])
        
        return command
    
    def __str__(self) -> str:
        """Get a string representation of the command."""
        return f"VoiceCommand(id={self.id}, text={self.text}, confidence={self.confidence:.2f})"
    
    def __repr__(self) -> str:
        """Get a string representation of the command."""
        return self.__str__()


class VoiceResponse:
    """
    Represents a voice response generated by the system.
    
    This class provides a standardized representation of voice responses
    for various synthesis engines.
    """
    
    def __init__(
        self,
        id: str,
        text: str,
        audio_data: Optional[bytes] = None,
        audio_format: str = "wav",
        voice_id: Optional[str] = None,
        timestamp: Optional[datetime.datetime] = None,
        metadata: Optional[Dict[str, Any]] = None,
    ):
        """
        Initialize a voice response.
        
        Args:
            id: The unique identifier for the response
            text: The text of the response
            audio_data: The audio data of the response
            audio_format: The format of the audio data
            voice_id: The ID of the voice used for synthesis
            timestamp: The timestamp of the response
            metadata: Additional metadata for the response
        """
        self.id = id
        self.text = text
        self.audio_data = audio_data
        self.audio_format = audio_format
        self.voice_id = voice_id
        self.timestamp = timestamp or datetime.datetime.now()
        self.metadata = metadata or {}
    
    @property
    def has_audio(self) -> bool:
        """Check if the response has audio data."""
        return self.audio_data is not None and len(self.audio_data) > 0
    
    @property
    def duration(self) -> Optional[float]:
        """Get the duration of the audio in seconds."""
        return self.metadata.get("duration")
    
    def to_dict(self) -> Dict[str, Any]:
        """
        Convert the response to a dictionary.
        
        Returns:
            A dictionary representation of the response
        """
        return {
            "id": self.id,
            "text": self.text,
            "audio_format": self.audio_format,
            "voice_id": self.voice_id,
            "timestamp": self.timestamp.isoformat() if self.timestamp else None,
            "metadata": self.metadata,
            "has_audio": self.has_audio,
            "duration": self.duration,
        }
    
    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "VoiceResponse":
        """
        Create a response from a dictionary.
        
        Args:
            data: The dictionary representation of the response
            
        Returns:
            A VoiceResponse object
        """
        timestamp = None
        if data.get("timestamp"):
            try:
                timestamp = datetime.datetime.fromisoformat(data["timestamp"])
            except ValueError:
                pass
        
        return cls(
            id=data.get("id", ""),
            text=data.get("text", ""),
            audio_data=None,  # Audio data is not included in the dictionary
            audio_format=data.get("audio_format", "wav"),
            voice_id=data.get("voice_id"),
            timestamp=timestamp,
            metadata=data.get("metadata", {}),
        )
    
    def save_audio(self, file_path: str) -> bool:
        """
        Save the audio data to a file.
        
        Args:
            file_path: The path to save the audio to
            
        Returns:
            True if saving was successful, False otherwise
        """
        if not self.has_audio:
            logger.warning("No audio data to save")
            return False
        
        try:
            with open(file_path, "wb") as f:
                f.write(self.audio_data)
            
            logger.info(f"Saved audio to {file_path}")
            return True
        except Exception as e:
            logger.error(f"Error saving audio to {file_path}: {e}", exc_info=True)
            return False
    
    def __str__(self) -> str:
        """Get a string representation of the response."""
        return f"VoiceResponse(id={self.id}, text={self.text}, has_audio={self.has_audio})"
    
    def __repr__(self) -> str:
        """Get a string representation of the response."""
        return self.__str__()


class VoiceEngine:
    """
    Base class for voice engines.
    
    This class defines the interface for voice recognition and synthesis
    engines and provides common functionality.
    """
    
    def __init__(self, config: Config):
        """
        Initialize a voice engine.
        
        Args:
            config: Application configuration
        """
        self.config = config
        self.name = "base"
    
    async def initialize(self):
        """Initialize the voice engine."""
        pass
    
    async def start_recognition(self) -> bool:
        """
        Start voice recognition.
        
        Returns:
            True if starting was successful, False otherwise
        """
        return False
    
    async def stop_recognition(self) -> bool:
        """
        Stop voice recognition.
        
        Returns:
            True if stopping was successful, False otherwise
        """
        return False
    
    async def recognize_audio(self, audio_data: bytes, audio_format: str = "wav") -> Optional[VoiceCommand]:
        """
        Recognize speech from audio data.
        
        Args:
            audio_data: The audio data to recognize
            audio_format: The format of the audio data
            
        Returns:
            A VoiceCommand object, or None if recognition failed
        """
        return None
    
    async def synthesize_speech(self, text: str, voice_id: Optional[str] = None) -> Optional[VoiceResponse]:
        """
        Synthesize speech from text.
        
        Args:
            text: The text to synthesize
            voice_id: The ID of the voice to use
            
        Returns:
            A VoiceResponse object, or None if synthesis failed
        """
        return None
    
    async def get_available_voices(self) -> List[Dict[str, Any]]:
        """
        Get the list of available voices.
        
        Returns:
            A list of voices
        """
        return []


class LocalVoiceEngine(VoiceEngine):
    """
    Local voice engine.
    
    This class provides a local implementation of voice recognition and
    synthesis using offline libraries.
    """
    
    def __init__(self, config: Config):
        """
        Initialize a local voice engine.
        
        Args:
            config: Application configuration
        """
        super().__init__(config)
        self.name = "local"
        self.recognizer = None
        self.synthesizer = None
        self.is_recognizing = False
        self.recognition_task = None
        self.voices = []
        self.default_voice_id = None
        self.recognition_callback = None
    
    async def initialize(self):
        """Initialize the local voice engine."""
        try:
            logger.info("Initializing local voice engine")
            
            self.voices = [
                {
                    "id": "default",
                    "name": "Default Voice",
                    "gender": "neutral",
                    "language": "en-US",
                },
                {
                    "id": "male",
                    "name": "Male Voice",
                    "gender": "male",
                    "language": "en-US",
                },
                {
                    "id": "female",
                    "name": "Female Voice",
                    "gender": "female",
                    "language": "en-US",
                },
            ]
            
            self.default_voice_id = "default"
            
            logger.info("Initialized local voice engine")
        except Exception as e:
            logger.error(f"Error initializing local voice engine: {e}", exc_info=True)
            raise
    
    async def start_recognition(self) -> bool:
        """
        Start voice recognition.
        
        Returns:
            True if starting was successful, False otherwise
        """
        if self.is_recognizing:
            logger.warning("Voice recognition is already running")
            return True
        
        try:
            logger.info("Starting voice recognition")
            
            self.is_recognizing = True
            
            self.recognition_task = asyncio.create_task(self._recognition_loop())
            
            return True
        except Exception as e:
            logger.error(f"Error starting voice recognition: {e}", exc_info=True)
            return False
    
    async def stop_recognition(self) -> bool:
        """
        Stop voice recognition.
        
        Returns:
            True if stopping was successful, False otherwise
        """
        if not self.is_recognizing:
            logger.warning("Voice recognition is not running")
            return True
        
        try:
            logger.info("Stopping voice recognition")
            
            self.is_recognizing = False
            
            if self.recognition_task:
                self.recognition_task.cancel()
                try:
                    await self.recognition_task
                except asyncio.CancelledError:
                    pass
                
                self.recognition_task = None
            
            return True
        except Exception as e:
            logger.error(f"Error stopping voice recognition: {e}", exc_info=True)
            return False
    
    async def _recognition_loop(self):
        """Recognition loop for continuous voice recognition."""
        logger.info("Starting recognition loop")
        
        try:
            while self.is_recognizing:
                await asyncio.sleep(10)
                
                if self.is_recognizing and self.recognition_callback:
                    command = VoiceCommand(
                        id=f"cmd_{datetime.datetime.now().timestamp()}",
                        text="Show me the latest documents",
                        confidence=0.9,
                    )
                    
                    await self.recognition_callback(command)
        except asyncio.CancelledError:
            logger.info("Recognition loop cancelled")
        except Exception as e:
            logger.error(f"Error in recognition loop: {e}", exc_info=True)
        
        logger.info("Recognition loop stopped")
    
    async def recognize_audio(self, audio_data: bytes, audio_format: str = "wav") -> Optional[VoiceCommand]:
        """
        Recognize speech from audio data.
        
        Args:
            audio_data: The audio data to recognize
            audio_format: The format of the audio data
            
        Returns:
            A VoiceCommand object, or None if recognition failed
        """
        try:
            command = VoiceCommand(
                id=f"cmd_{datetime.datetime.now().timestamp()}",
                text="This is a simulated voice command",
                confidence=0.8,
            )
            
            return command
        except Exception as e:
            logger.error(f"Error recognizing audio: {e}", exc_info=True)
            return None
    
    async def synthesize_speech(self, text: str, voice_id: Optional[str] = None) -> Optional[VoiceResponse]:
        """
        Synthesize speech from text.
        
        Args:
            text: The text to synthesize
            voice_id: The ID of the voice to use
            
        Returns:
            A VoiceResponse object, or None if synthesis failed
        """
        try:
            response = VoiceResponse(
                id=f"resp_{datetime.datetime.now().timestamp()}",
                text=text,
                voice_id=voice_id or self.default_voice_id,
            )
            
            return response
        except Exception as e:
            logger.error(f"Error synthesizing speech: {e}", exc_info=True)
            return None
    
    async def get_available_voices(self) -> List[Dict[str, Any]]:
        """
        Get the list of available voices.
        
        Returns:
            A list of voices
        """
        return self.voices
    
    def set_recognition_callback(self, callback: Callable[[VoiceCommand], Any]):
        """
        Set the callback for voice recognition.
        
        Args:
            callback: The callback function to call when a command is recognized
        """
        self.recognition_callback = callback


class CloudVoiceEngine(VoiceEngine):
    """
    Cloud voice engine.
    
    This class provides integration with cloud-based voice recognition and
    synthesis services.
    """
    
    def __init__(self, config: Config):
        """
        Initialize a cloud voice engine.
        
        Args:
            config: Application configuration
        """
        super().__init__(config)
        self.name = "cloud"
        self.provider = config.get("voice.cloud.provider", "google")
        self.api_key = config.get(f"voice.cloud.{self.provider}.api_key")
        self.region = config.get(f"voice.cloud.{self.provider}.region")
        self.client = None
    
    async def initialize(self):
        """Initialize the cloud voice engine."""
        try:
            logger.info(f"Initializing cloud voice engine ({self.provider})")
            
            if not self.api_key:
                logger.warning(f"No API key provided for {self.provider} voice engine")
            
            logger.info(f"Initialized cloud voice engine ({self.provider})")
        except Exception as e:
            logger.error(f"Error initializing cloud voice engine: {e}", exc_info=True)
            raise


class VoiceIntent(Enum):
    """Intents that can be recognized from voice commands."""
    
    SEARCH = auto()  # Search for documents
    OPEN = auto()  # Open a document
    CREATE = auto()  # Create a document
    DELETE = auto()  # Delete a document
    SHARE = auto()  # Share a document
    SUMMARIZE = auto()  # Summarize a document
    ANALYZE = auto()  # Analyze a document
    HELP = auto()  # Get help
    SETTINGS = auto()  # Change settings
    UNKNOWN = auto()  # Unknown intent


class VoiceService:
    """
    Service for voice interaction.
    
    This service provides voice recognition and synthesis capabilities
    for natural language interaction with the application.
    """
    
    def __init__(self, config: Config):
        """
        Initialize the voice service.
        
        Args:
            config: Application configuration
        """
        self.config = config
        self.is_running = False
        self.engines = {}
        self.default_engine = None
        self.is_listening = False
        self.wake_word = config.get("voice.wake_word", "assistant")
        self.intent_parser = None
        
        self._load_config()
    
    def _load_config(self):
        """Load configuration from the config object."""
        self.enabled = self.config.get("voice.enabled", True)
        self.wake_word_enabled = self.config.get("voice.wake_word_enabled", True)
        self.continuous_listening = self.config.get("voice.continuous_listening", False)
        self.default_engine_name = self.config.get("voice.default_engine", "local")
        self.default_voice_id = self.config.get("voice.default_voice_id")
        
        self.engine_configs = self.config.get("voice.engines", {})
    
    async def initialize(self):
        """Initialize the voice service."""
        if not self.enabled:
            logger.info("Voice service is disabled in configuration")
            return
        
        logger.info("Initializing voice service")
        
        try:
            local_engine = LocalVoiceEngine(self.config)
            await local_engine.initialize()
            self.engines[local_engine.name] = local_engine
            
            if self.engine_configs.get("cloud", {}).get("enabled", False):
                cloud_engine = CloudVoiceEngine(self.config)
                await cloud_engine.initialize()
                self.engines[cloud_engine.name] = cloud_engine
            
            if self.default_engine_name in self.engines:
                self.default_engine = self.engines[self.default_engine_name]
            else:
                self.default_engine = self.engines.get("local")
            
            await self._initialize_intent_parser()
            
            event_bus.subscribe(EventType.VOICE_COMMAND_RECOGNIZED, self._on_command_recognized)
            event_bus.subscribe(EventType.VOICE_RESPONSE_GENERATED, self._on_response_generated)
            
            logger.info("Voice service initialized")
        except Exception as e:
            logger.error(f"Error initializing voice service: {e}", exc_info=True)
            raise
    
    async def _initialize_intent_parser(self):
        """Initialize the intent parser for voice commands."""
        self.intent_parser = {
            "search": VoiceIntent.SEARCH,
            "find": VoiceIntent.SEARCH,
            "look for": VoiceIntent.SEARCH,
            "open": VoiceIntent.OPEN,
            "show": VoiceIntent.OPEN,
            "display": VoiceIntent.OPEN,
            "create": VoiceIntent.CREATE,
            "new": VoiceIntent.CREATE,
            "make": VoiceIntent.CREATE,
            "delete": VoiceIntent.DELETE,
            "remove": VoiceIntent.DELETE,
            "share": VoiceIntent.SHARE,
            "send": VoiceIntent.SHARE,
            "summarize": VoiceIntent.SUMMARIZE,
            "summary": VoiceIntent.SUMMARIZE,
            "analyze": VoiceIntent.ANALYZE,
            "help": VoiceIntent.HELP,
            "settings": VoiceIntent.SETTINGS,
            "configure": VoiceIntent.SETTINGS,
        }
    
    async def start(self):
        """Start the voice service."""
        if not self.enabled:
            logger.info("Voice service is disabled in configuration")
            return
        
        if self.is_running:
            logger.warning("Voice service is already running")
            return
        
        logger.info("Starting voice service")
        
        self.is_running = True
        
        if self.continuous_listening:
            await self.start_listening()
        
        logger.info("Voice service started")
    
    async def stop(self):
        """Stop the voice service."""
        if not self.is_running:
            logger.warning("Voice service is not running")
            return
        
        logger.info("Stopping voice service")
        
        self.is_running = False
        
        if self.is_listening:
            await self.stop_listening()
        
        logger.info("Voice service stopped")
    
    async def start_listening(self) -> bool:
        """
        Start listening for voice commands.
        
        Returns:
            True if starting was successful, False otherwise
        """
        if not self.is_running:
            logger.warning("Voice service is not running")
            return False
        
        if self.is_listening:
            logger.warning("Already listening for voice commands")
            return True
        
        logger.info("Starting to listen for voice commands")
        
        try:
            for engine_name, engine in self.engines.items():
                if hasattr(engine, "set_recognition_callback"):
                    engine.set_recognition_callback(self._handle_voice_command)
            
            if self.default_engine:
                success = await self.default_engine.start_recognition()
                if success:
                    self.is_listening = True
                    
                    publish(
                        EventType.VOICE_LISTENING_STARTED,
                        {
                            "engine": self.default_engine.name,
                        },
                    )
                    
                    return True
            
            logger.error("Failed to start listening for voice commands")
            return False
        except Exception as e:
            logger.error(f"Error starting to listen for voice commands: {e}", exc_info=True)
            return False
    
    async def stop_listening(self) -> bool:
        """
        Stop listening for voice commands.
        
        Returns:
            True if stopping was successful, False otherwise
        """
        if not self.is_listening:
            logger.warning("Not listening for voice commands")
            return True
        
        logger.info("Stopping listening for voice commands")
        
        try:
            if self.default_engine:
                success = await self.default_engine.stop_recognition()
                if success:
                    self.is_listening = False
                    
                    publish(
                        EventType.VOICE_LISTENING_STOPPED,
                        {
                            "engine": self.default_engine.name,
                        },
                    )
                    
                    return True
            
            logger.error("Failed to stop listening for voice commands")
            return False
        except Exception as e:
            logger.error(f"Error stopping listening for voice commands: {e}", exc_info=True)
            return False
    
    async def _handle_voice_command(self, command: VoiceCommand):
        """
        Handle a voice command.
        
        Args:
            command: The voice command to handle
        """
        logger.info(f"Handling voice command: {command.text}")
        
        try:
            if not command.is_confident:
                logger.warning(f"Command confidence too low: {command.confidence:.2f}")
                return
            
            if self.wake_word_enabled and self.wake_word:
                if not self.wake_word.lower() in command.text.lower():
                    logger.debug(f"Wake word not detected in command: {command.text}")
                    return
                
                command.text = re.sub(rf"\b{re.escape(self.wake_word)}\b", "", command.text, flags=re.IGNORECASE).strip()
            
            command.intent = self._parse_intent(command.text)
            
            command.entities = self._extract_entities(command.text, command.intent)
            
            publish(
                EventType.VOICE_COMMAND_RECOGNIZED,
                {
                    "command": command.to_dict(),
                },
            )
        except Exception as e:
            logger.error(f"Error handling voice command: {e}", exc_info=True)
    
    def _parse_intent(self, text: str) -> VoiceIntent:
        """
        Parse the intent from a voice command.
        
        Args:
            text: The text of the command
            
        Returns:
            The intent of the command
        """
        text_lower = text.lower()
        
        for keyword, intent in self.intent_parser.items():
            if keyword in text_lower:
                return intent
        
        return VoiceIntent.UNKNOWN
    
    def _extract_entities(self, text: str, intent: VoiceIntent) -> List[Dict[str, Any]]:
        """
        Extract entities from a voice command.
        
        Args:
            text: The text of the command
            intent: The intent of the command
            
        Returns:
            A list of entities
        """
        entities = []
        
        
        if intent == VoiceIntent.SEARCH:
            match = re.search(r"(?:search|find|look for)\s+(.+)", text, re.IGNORECASE)
            if match:
                entities.append({
                    "type": "query",
                    "value": match.group(1),
                })
        elif intent == VoiceIntent.OPEN:
            match = re.search(r"(?:open|show|display)\s+(.+)", text, re.IGNORECASE)
            if match:
                entities.append({
                    "type": "document",
                    "value": match.group(1),
                })
        
        return entities
    
    async def recognize_audio(
        self,
        audio_data: bytes,
        audio_format: str = "wav",
        engine_name: Optional[str] = None,
    ) -> Optional[VoiceCommand]:
        """
        Recognize speech from audio data.
        
        Args:
            audio_data: The audio data to recognize
            audio_format: The format of the audio data
            engine_name: The name of the engine to use
            
        Returns:
            A VoiceCommand object, or None if recognition failed
        """
        engine = None
        
        if engine_name:
            engine = self.engines.get(engine_name)
            if not engine:
                logger.warning(f"Voice engine {engine_name} not found")
                return None
        else:
            engine = self.default_engine
        
        if not engine:
            logger.error("No voice engine available")
            return None
        
        command = await engine.recognize_audio(audio_data, audio_format)
        
        if command:
            command.intent = self._parse_intent(command.text)
            command.entities = self._extract_entities(command.text, command.intent)
            
            publish(
                EventType.VOICE_COMMAND_RECOGNIZED,
                {
                    "command": command.to_dict(),
                },
            )
        
        return command
    
    async def synthesize_speech(
        self,
        text: str,
        voice_id: Optional[str] = None,
        engine_name: Optional[str] = None,
    ) -> Optional[VoiceResponse]:
        """
        Synthesize speech from text.
        
        Args:
            text: The text to synthesize
            voice_id: The ID of the voice to use
            engine_name: The name of the engine to use
            
        Returns:
            A VoiceResponse object, or None if synthesis failed
        """
        engine = None
        
        if engine_name:
            engine = self.engines.get(engine_name)
            if not engine:
                logger.warning(f"Voice engine {engine_name} not found")
                return None
        else:
            engine = self.default_engine
        
        if not engine:
            logger.error("No voice engine available")
            return None
        
        response = await engine.synthesize_speech(text, voice_id or self.default_voice_id)
        
        if response:
            publish(
                EventType.VOICE_RESPONSE_GENERATED,
                {
                    "response": response.to_dict(),
                },
            )
        
        return response
    
    async def get_available_voices(self, engine_name: Optional[str] = None) -> List[Dict[str, Any]]:
        """
        Get the list of available voices.
        
        Args:
            engine_name: The name of the engine to get voices from
            
        Returns:
            A list of voices
        """
        if engine_name:
            engine = self.engines.get(engine_name)
            if not engine:
                logger.warning(f"Voice engine {engine_name} not found")
                return []
            
            return await engine.get_available_voices()
        else:
            voices = []
            for engine_name, engine in self.engines.items():
                engine_voices = await engine.get_available_voices()
                for voice in engine_voices:
                    voice["engine"] = engine_name
                
                voices.extend(engine_voices)
            
            return voices
    
    async def _on_command_recognized(self, event):
        """
        Handle voice command recognized events.
        
        Args:
            event: The voice command recognized event
        """
        logger.info(f"Voice command recognized: {event.data.get('command', {}).get('text')}")
    
    async def _on_response_generated(self, event):
        """
        Handle voice response generated events.
        
        Args:
            event: The voice response generated event
        """
        logger.info(f"Voice response generated: {event.data.get('response', {}).get('text')}")
